import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';

const rootDir = process.cwd();
const contentDir = path.join(rootDir, 'public', 'content');
const outputFile = path.join(rootDir, 'lib', 'content-data.ts');

function readMarkdown(filePath) {
  const fileContents = fs.readFileSync(filePath, 'utf8');
  return matter(fileContents);
}

function getArticlesForLocale(locale) {
  const typeDir = locale === 'de' ? 'ratgeber' : 'advisor';
  const articlesDir = path.join(contentDir, locale, typeDir);

  if (!fs.existsSync(articlesDir)) {
    return {};
  }

  const folders = fs.readdirSync(articlesDir);
  const articles = {};

  for (const folder of folders) {
    const articlePath = path.join(articlesDir, folder, 'article.md');
    if (!fs.existsSync(articlePath)) continue;

    const { data, content } = readMarkdown(articlePath);
    const wordCount = content.split(/\s+/).length;
    const readingTime = Math.ceil(wordCount / 200);

    articles[folder] = {
      meta: {
        title: data.title || '',
        description: data.description || '',
        slug: folder,
        category: data.category || '',
        author: data.author || '',
        date: data.date || '',
        readingTime,
        lang: locale,
        image: data.image || undefined,
      },
      content,
    };
  }

  return articles;
}

function getLegalDoc(relPath) {
  const fullPath = path.join(contentDir, relPath);
  if (!fs.existsSync(fullPath)) {
    throw new Error(`Required legal document missing: ${fullPath}`);
  }
  const { content } = readMarkdown(fullPath);
  return content;
}

const deArticles = getArticlesForLocale('de');
const enArticles = getArticlesForLocale('en');

const legalDocs = {
  'impressum': getLegalDoc('de/legal/impressum.md'),
  'datenschutz': getLegalDoc('de/privacy/datenschutz.md'),
  'legal': getLegalDoc('en/legal/legal.md'),
  'privacy': getLegalDoc('en/privacy/privacy.md'),
};

const fileContent = `// Auto-generated by scripts/generate-content.mjs - DO NOT EDIT DIRECTLY
export interface ArticleMeta {
  title: string;
  description: string;
  slug: string;
  category: string;
  author: string;
  date: string;
  readingTime: number;
  lang: 'de' | 'en';
  image?: string;
}

export interface ArticleItem {
  meta: ArticleMeta;
  content: string;
}

export const articlesData: Record<'de' | 'en', Record<string, ArticleItem>> = ${JSON.stringify({ de: deArticles, en: enArticles }, null, 2)};

export const legalDocsData: Record<'impressum' | 'datenschutz' | 'legal' | 'privacy', string> = ${JSON.stringify(legalDocs, null, 2)};
`;

fs.writeFileSync(outputFile, fileContent, 'utf8');
console.log(`Successfully generated ${outputFile}`);
console.log(`- DE Articles: ${Object.keys(deArticles).length}`);
console.log(`- EN Articles: ${Object.keys(enArticles).length}`);
console.log(`- Legal Documents: ${Object.keys(legalDocs).length}`);
